### ISSUE TITLE
A tiny suggestion for adding parameter in sambamba

### ISSUE THREAD

**Issue by xiaoyufeixue** [likelet/LncPipe#1]
I have to say that LncPipe is so friendly and easy to use . But there was a tiny suggestion at line 553 ‘sambamba sort .......’, it will be nice to add the parameter  '--tmpdir', because my server's system storage was not big enough for storing the intermediate files and my tasks were dropped with the error 'not enough space on /tmp'. Anyway, it was not a problem for those friends with big enough system storage.

**Comment by likelet** [comment]
Thanks for your suggestion! 
I have already add the this parameter in nf file and the tmp folder is now setting on the current path. 
plz see [7c6ae7c](https://github.com/likelet/LncPipe/commit/7c6ae7cdb19510495d3aaab8ee9e975edbdac9d0)
