### ISSUE TITLE
Workflow_Image

### ISSUE THREAD

**Issue by sateeshperi** [likelet/LncPipe#10]
Since LncPipe allows for user-selection of tools for different steps, is it possible to have a visual map of the tools used by the user at the end of the pipeline? 
I know in Snakemake we can output an DAG of jobs like this (https://goo.gl/BuiiJF), can we get a similar output either in the reporter.html or separately to help in publications. Let me know your thoughts

**Comment by likelet** [comment]
we do have this feature inherent from Nextflow. The conrepnstonding command is  
```
      nextflow run <script-name> -with-dag flowchart.png
```

The detailed information can be found [here](https://www.nextflow.io/docs/latest/tracing.html)
But you need make sure that the  Graphviz tool have  installed in your computer if you are going to get pdf, png or svg file format 

plz let me know you if have more question

**Comment by sateeshperi** [comment]
Please correct me if I am wrong but, I guess this command will have to be run when launching the pipeline. There is no way to get just the dag after running the pipeline, right?

**Comment by likelet** [comment]
yes， you are right so far as i know :)
