### ISSUE TITLE
coding_abilities_by_CNCI?

### ISSUE THREAD

**Issue by sateeshperi** [likelet/LncPipe#14]
Is LncPipe currently predicting coding abilities by CNCI? I was examining the nextflow dag of jobs for one of my runs of LncPipe (see attached) and saw that the novelLncRNAFasta_for_CNCI is not leading to a CNCI job! 
![bgi_c3n3](https://user-images.githubusercontent.com/33637490/44498139-ab290280-a631-11e8-903f-d1279e4b1217.png)

**Comment by likelet** [comment]
yes，we previously using cnci to do so, but we find that the cnci process  unexpectly stoped without return errors. so it is deprecated in the current version. to note, the cnci input channel do nothing for the result, we just leave an interface for futher implementation.😁

**Comment by sateeshperi** [comment]
Understood. Can i then recommend updating the description section of 'lncRNA.Rmd' in LncPipeReporter as it still describes the plotting using CNCI?
```
 In LncPipe, coding poteintial of final lncRNAs were reassesed by CNCI, so CNCI CDS data were plot accordingly which coding genes were also considered;
```

**Comment by likelet** [comment]
yep， it's using cpat output for ploting now.
