### ISSUE TITLE
Error_"htseq can not be applicable without mapping step, plz set quant tool using `kallisto`"

### ISSUE THREAD

**Issue by sateeshperi** [likelet/LncPipe#16]
I am getting an error resuming with --merged_gtf option when using "htseq". What is the main purpose of this exit code in the nf file?
```
if(params.quant=="htseq"){
        exit 0, print_red("htseq can not be applicable without mapping step, plz set quant tool using `kallisto`")
```

**Comment by likelet** [comment]
Yes, actually, when using --merged_gtf option, it means you have already done with mapping and assembly steps, but "htseq" need bam file(need remapping from fastq) for quantification that may take comparative time to  running from the very beginning . So, I did not plan to implement this option when using htseq.
