### ISSUE TITLE
ERROR ~ No such variable: readPairs_for_kallisto

### ISSUE THREAD

**Issue by hovans** [likelet/LncPipe#2]
I set the parameter " --merged_gtf my_merged.gtf " to skip the QC and assemble, but got an error "ERROR ~ No such variable: readPairs_for_kallisto". The following is my cmd: " nextflow run ./LncPipe-master/LncRNAanalysisPipe.nf --input_folder ./0.data/ --out_folder ./test_v1/ --design ./design.file --merged_gtf ./test_v1/Result/Merged_assemblies/merged.gtf". Please tell me if my cmd was not suitable or there was any problem in the main script of LncRNAanalysisPipe.nf, waiting for your attention.

**Comment by likelet** [comment]
Yes, this is actually a bug at previous version of LncPipe. 
It was fixed along with the latest commit. Plz checkout the latest version code from git repo instead.
