### ISSUE TITLE
Error initializing class

### ISSUE THREAD

**Issue by sateeshperi** [likelet/LncPipe#24]
https://github.com/likelet/LncPipe/blob/4b3447c3bd36d603107677fb41d42c0d94748fa7/LncRNAanalysisPipe.nf#L274

There still seems to be a problem with the .into initialization. can this be coded in some other way, or should this also be initiated as a channel as done for the 'human' prepare annotation channel?

**Comment by likelet** [comment]
ok，i will check this soon

**Comment by likelet** [comment]
hi sateesh, 
i did not see the error on my side , can u plz paste the error in here

**Comment by sateeshperi** [comment]
```
Combining known annotations from GTFs
ERROR ~ No signature of method: sun.nio.fs.UnixPath.set() is applicable for argument types: (_nf_script_18293a4f$_run_closure14) values: [_nf_script_18293a4f$_run_closure14@4602c2a9]
Possible solutions: sort(), sum(), toSet(), sort(groovy.lang.Closure), sum(java.lang.Object), sort(boolean)

 -- Check script 'LncRNAanalysisPipe.nf' at line: 270 or see '.nextflow.log' file for more details
```
I am running the pipeline for non-model organism rat so, it is initiating '266-277' lines of code in the nf file
[nextflow_log.txt](https://github.com/likelet/LncPipe/files/2490534/nextflow_log.txt)
[docker.config.txt](https://github.com/likelet/LncPipe/files/2490538/docker.config.txt)

**Comment by brunohhomem** [comment]
I'm having the same error but it occurs on line 284 of the code.. any suggestion?

WARN: Access to undefined parameter `cpu` -- Initialise it to a default value eg. `params.cpu = some_value`
Combining known annotations from GTFs
ERROR ~ No signature of method: sun.nio.fs.UnixPath.into() is applicable for argument types: (_nf_script_3896f0c8$_run_closure14) values: [_nf_script_3896f0c8$_run_closure14@22101c80]
Possible solutions: init(), inits(), find(), any(), list(), min()

 -- Check script 'LncRNAanalysisPipe.nf' at line: 284 or see '.nextflow.log' file for more details

**Comment by likelet** [comment]
@brunohhomem where did this error come from? (when run test dataset ? or your own dataset ?)  and what is your Nextflow version? 
thanks !

**Comment by brunohhomem** [comment]
my own dataset, I'm running with nextflow version 18.10.1 cause with any version after 18.10.1, the pipeline give an error like below, and @pditommaso suggested that they could be because "This pipeline is defining multiple times the same process name which is not allowed any more is latest NF version".

> _"blur@epi_lab:~$ sudo nextflow run nf-core/lncpipe -profile docker
> N E X T F L O W ~ version 19.01.0
> Launching `nf-core/lncpipe` [chaotic_curran] - revision: [464f015](https://github.com/nf-core/lncpipe/commit/464f015763be5e15c81a385fbe7bcda7dc9ae7e7) [master]
> ERROR ~ Process `Run_fastQC` is already define @ line 849, column 17.
> process Run_fastQC {
> ^
> 
> _nf_script_3896f0c8: 875: Process `Run_afterQC` is already define @ line 875, column 17.
> process Run_afterQC {
> ^
> 
> _nf_script_3896f0c8: 909: Process `Run_FastP` is already define @ line 909, column 17.
> process Run_FastP {
> ^
> 
> _nf_script_3896f0c8: 1443: Process `Build_kallisto_index_of_GTF_for_quantification` is already define @ line 1443, column 17.
> process Build_kallisto_index_of_GTF_for_quantification {
> ^
> 
> _nf_script_3896f0c8: 1460: Process `Run_kallisto_for_quantification` is already define @ line 1460, column 17.
> process Run_kallisto_for_quantification {
> ^
> 
> _nf_script_3896f0c8: 1582: Process `Run_LncPipeReporter` is already define @ line 1582, column 17.
> process Run_LncPipeReporter {
> ^
> 
> _nf_script_3896f0c8: 1628: Process `Run_LncPipeReporter_without_Design` is already define @ line 1628, column 17.
> process Run_LncPipeReporter_without_Design {
> ^
> 
> 7 errors
> 
> -- Check '.nextflow.log' file for details"_


Edit: I'll try to run with the lnc test data.

**Comment by likelet** [comment]
this error has been fixed by renaming the process names and also added a FAQ in  the readme file. 
Yes, plz try the testdata first.

**Comment by brunohhomem** [comment]
I tried run the analisys of the test data and worked. 
Returning to the error of nextflow version, I redownloaded everything (nextflow 19 and pipe "lastest"). The lncpipe from this link "https://github.com/nf-core/lncpipe/archive/master.zip" and the error has appeared. The version pulled from nf-core repository shows the same error. What is the last version of pipe? Cause every version avaiable thought nf-core/lncpipe shows the same error of multiple process on nextflow > 18.10.1.
Should I only use the older nextflow code? Cause I'm following the tips trying to use the latest codes.

**Comment by likelet** [comment]
> I tried run the analisys of the test data and worked.
> Returning to the error of nextflow version, I redownloaded everything (nextflow 19 and pipe "lastest"). The lncpipe from this link "https://github.com/nf-core/lncpipe/archive/master.zip" and the error has appeared. The version pulled from nf-core repository shows the same error. What is the last version of pipe? Cause every version avaiable thought nf-core/lncpipe shows the same error of multiple process on nextflow > 18.10.1.
> Should I only use the older nextflow code? Cause I'm following the tips trying to use the latest codes.

sorry for not write clearly,  the latest version has not been released yet, plz get the code using `git clone` command. For example 
```bash
git clone https://github.com/likelet/LncPipe.git
```

BTW, the version from nf-core is still under development, although it may functionally work for `0.18.10.1` nextflow

**Comment by brunohhomem** [comment]
> > I tried run the analisys of the test data and worked.
> > Returning to the error of nextflow version, I redownloaded everything (nextflow 19 and pipe "lastest"). The lncpipe from this link "https://github.com/nf-core/lncpipe/archive/master.zip" and the error has appeared. The version pulled from nf-core repository shows the same error. What is the last version of pipe? Cause every version avaiable thought nf-core/lncpipe shows the same error of multiple process on nextflow > 18.10.1.
> > Should I only use the older nextflow code? Cause I'm following the tips trying to use the latest codes.
> 
> sorry for not write clearly, the latest version has not been released yet, plz get the code using `git clone` command. For example
> 
> ```shell
> git clone https://github.com/likelet/LncPipe.git
> ```
> 
> BTW, the version from nf-core is still under development, although it may functionally work for `0.18.10.1` nextflow

Yep, I did that, and worked through the error of multiple process.

**Comment by brunohhomem** [comment]
I've made a lot of tests trying to figure how to make my data work on the pipeline. I'm trying use the pipeline on mouse data and even I giving the reference data, the pipeline can't find where the data is. My problem is similar to @sateeshperi 's error:
gencode_annotation_gtf.into{proteinCodingGTF; proteinCodingGTF_forClass}

Then, I've tried to run my dataset as "human" rather than "mouse", and kind of worked (For making the test I used LNCipedia from LncPipeTestData, cause "human" paramns requires LNCipedia).
I wonder, if the part of the code of "mouse" aren't incomplete cause the "human" code has much more code than "mouse" even mouse requiring more gtf reference.

I'm not a programmer, so sorry for making so much questions and bring so many issues.
I'll attach the nextflow.log for references.
[nextflow.log](https://github.com/likelet/LncPipe/files/2885588/nextflow.log)

**Comment by brunohhomem** [comment]
> I've made a lot of tests trying to figure how to make my data work on the pipeline. I'm trying use the pipeline on mouse data and even I giving the reference data, the pipeline can't find where the data is. My problem is similar to @sateeshperi 's error:
> gencode_annotation_gtf.into{proteinCodingGTF; proteinCodingGTF_forClass}
> 
> Then, I've tried to run my dataset as "human" rather than "mouse", and kind of worked (For making the test I used LNCipedia from LncPipeTestData, cause "human" paramns requires LNCipedia).
> I wonder, if the part of the code of "mouse" aren't incomplete cause the "human" code has much more code than "mouse" even mouse requiring more gtf reference.
> 
> I'm not a programmer, so sorry for making so much questions and bring so many issues.
> I'll attach the nextflow.log for references.
> [nextflow.log](https://github.com/likelet/LncPipe/files/2885588/nextflow.log)

**Comment by likelet** [comment]
Hi Bruno 
Sorry for not say clearly in the documentation and many thanks for test the code. 
Actually, it's totally wrong to set the species to "human" to run mouse data.  Because the combination step only was only designed for human species. For other species, the pipeline skipped the annotation integration step and need users providing `known_coding` and `known_lncRNA` gtf file in the config file accordingly.   We realized that the annotations for human were more abundant than any other animals. Therefore the combination annotation could largely benefit this kind of analysis, and surely need more code for this. 

to run it for your situation, plz set the path of  `known_coding_gtf` and `known_lncRNA_gtf`. 
which two files could be generated by `grep ` command .  For example, `grep protein_coding your_gencode_gtf`   for protein_coding_gtf. 
we are sorry that we can not process it automatedly because we have encountered so many different GTF formats in different situation. 
Plz let me know if I have to refine code. 

Qi

**Comment by brunohhomem** [comment]
> Hi Bruno
> Sorry for not say clearly in the documentation and many thanks for test the code.
> Actually, it's totally wrong to set the species to "human" to run mouse data. Because the combination step only was only designed for human species. For other species, the pipeline skipped the annotation integration step and need users providing `known_coding` and `known_lncRNA` gtf file in the config file accordingly. We realized that the annotations for human were more abundant than any other animals. Therefore the combination annotation could largely benefit this kind of analysis, and surely need more code for this.
> 
> to run it for your situation, plz set the path of `known_coding_gtf` and `known_lncRNA_gtf`.
> which two files could be generated by `grep ` command . For example, `grep protein_coding your_gencode_gtf` for protein_coding_gtf.
> we are sorry that we can not process it automatedly because we have encountered so many different GTF formats in different situation.
> Plz let me know if I have to refine code.
> 
> Qi

Yes, I suspected that I should not run mouse data as "human", I just tested a theory.
And for the GTF files I'm following the documentation of the pipe, I'm using the README for non human especies. I've tried to use the GTF reference files, that are described on the readme file. I did the grep command on the gencode annotation suggested in README file. I also tried with new GTF reference downloaded directly from https://www.gencodegenes.org/mouse/ and it still did not work either.

-Bruno

**Comment by likelet** [comment]
I will test mouse locally again for your case and will let you know the progress.

**Comment by brunohhomem** [comment]
Thanks, I really appreciate.

**Comment by brunohhomem** [comment]
Hey, any news?

> I will test mouse locally again for your case and will let you know the progress.

**Comment by likelet** [comment]
sorry for the delayed response. I have updated the code for run non-human samples, and it tested smoothly on my local data. You can try `git clone` the latest version for run mouse samples on your side. 
However, there is still a bug in lncPipeReporter to parsing the results of lncPipe, I have talked to the author of the package. He is now experiencing a hard time for his graduation dissertation and will fix the bug then.
