### ISSUE TITLE
  Process `Run_LncPipeReporter (Generating report ...)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by drejom** [likelet/LncPipe#26]
I'm  getting this error when running the pipeline using Singularity - it fails at the LncPipeReporter process:

```
...
processing file: ./edger.Rmd
TIFFAppendToStrip: Write error at scanline 2550.
Quitting from lines 65-77 (./edger.Rmd)
Quitting from lines 250-255 (./edger.Rmd)
Error in grDevices::dev.off() : write failed
Calls: run_reporter ... evalVis -> withVisible -> eval -> eval -> <Anonymous>
Execution halted
```
I can run the report manually from the local R installation, so I think it's an issue with the Docker image?

**Comment by likelet** [comment]
yes , this problem has not been fixed yet. But the docker run test has already been passed. I am looking into it trying find a solution. you can temporally comment the reporter process to do further test.

**Comment by drejom** [comment]
I tried rerunning this with a locally built singularity image using your Dockerfile, but the pipeline still fails at this step with a different error:

```
processing file: ./Hisat2.Rmd
  Taking input= as a system command ('grep -H '' [FILENAMES CLIPPED FOR READABILITY] | perl -F':|\(|\)|(>?\d\stimes?)' -lanE '/%/ and /aligned/ ? say join qq{      }, @F : next'') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure envionment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.

  processing file: ./edger.Rmd
  Taking input= as a system command ('perl -F':|,' -lanE'BEGIN{say qq{SampleID  condition}} $fuck = shift @F; say qq{$_ $fuck} for @F' design.file') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure envionment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.
  Quitting from lines 65-77 (./edger.Rmd)
  Quitting from lines 250-255 (./edger.Rmd)
  Error in grDevices::dev.off() : write failed
  Calls: run_reporter ... evalVis -> withVisible -> eval -> eval -> <Anonymous>
  Execution halted
``` 
When I run it with the local R 3.4.2 installation on our cluster, it finishes but outputs the following warnings:

```
Output created: reporter.html
Warning messages:
1: In grDevices::dev.off() : No TIFF support in this version of R
2: In grDevices::dev.off() : No TIFF support in this version of R
3: Removed 1 rows containing missing values (geom_point). 
4: In grDevices::dev.off() : No TIFF support in this version of R
5: Removed 1 rows containing missing values (geom_point). 
6: In grDevices::dev.off() : No TIFF support in this version of R
7: In grDevices::dev.off() : No TIFF support in this version of R
```
This suggests a problem with the R installation in the container. I notice that the Dockerfile in this repo and that on [dockerhub](https://hub.docker.com/r/bioinformatist/lncpipe/~/dockerfile/) differ specifically in the installation of R (and a number of formatting changes that prevent the repo Dockerfile from working.) 

I've made some edits to the Dockerfile and am trying again with R 3.4.2 - will let you know if it works. Or do you have any hints for getting a working container?

**Comment by likelet** [comment]
thanks for pointing it out, this is still a problem, i am trying to build the Singularity separately from dockerfile. BTW, i have already port it into nf-core to ask help from nf-core team.  https://github.com/nf-core/lncpipe, you can also open issue there and plz also let me know how it works.
Best wishes!

**Comment by drejom** [comment]
Ok, great! I have a few immediate suggestions for per-process resource requests in line with nf-core. Will make a PR for your review - or should I move it to that repo, once theres a dev branch? Looks like the nf-core team are already fast at work.

**Comment by likelet** [comment]
yep, thanks for all you did. the `dev` branch has already be opened for test, i will keep on develop for his pipe in the `dev` branch there.  
thanks Denis.
