### ISSUE TITLE
Process "Summary_renaming_and_classification (1)" terminated with an error exit status (2)

### ISSUE THREAD

**Issue by brunohhomem** [likelet/LncPipe#27]
Hi, i'm trying to run some analysis on pipe, and I've found this error.
Before this error, I've found errors 137 and 134 from kallisto quantification, so I reduced the "para" and "qc" paramms on docker.config (6 to 2), them this error has appeared. Any clue of I can do to fix this problem?
[nextflow2.log](https://github.com/likelet/LncPipe/files/2507164/nextflow2.log)

**Comment by likelet** [comment]
seems something went wrong in rename step, can you plz packing the file from folder `/home/bruno/work/14/77f8c83efc49341d4d3878abef8e6e`
and send me by zhaoqi@sysucc.org.cn
thanks !

**Comment by brunohhomem** [comment]
I've tried to re-run the pipe, testing other params, so I didn't save that folder /14/f8c83efc49341d4d3878abef8e6e, but I'm sending you the folder of the last attempt, and the logs too.

**Comment by likelet** [comment]
well, i got your mail and am going to have a check of your data. 
i will give you a reply once i figured it out.

**Comment by likelet** [comment]
@brunohhomem ， plz try `git clone ` the latest commit , sorry for the delay response   

Qi
