### ISSUE TITLE
Pipeline not working with Nextflow latest version 18.10.1

### ISSUE THREAD

**Issue by athulmenon** [likelet/LncPipe#30]
Does it need the older versions of Nextflow to run? It shows this error when I tried to run the pipeline.

This workflow requires Nextflow version 0.26 or greater -- You are running version 18.10.1

Athul

**Comment by likelet** [comment]
i am sorry that  the current the latest release should run  with Nextflow >0.30.   (i will fix the code soon)

Qi 

plz also paste the error info here

**Comment by liuteng-dandiaoliutuo** [comment]
WARN: It appears you have never run this project before -- Option `-resume` is ignored
WARN: Process `Run_fastQC` is defined two or more times
WARN: Process `Run_afterQC` is defined two or more times
WARN: Process `Run_FastP` is defined two or more times
WARN: Process `Build_kallisto_index_of_GTF_for_quantification` is defined two or more times
WARN: Process `Run_kallisto_for_quantification` is defined two or more times
WARN: Process `Run_LncPipeReporter` is defined two or more times
WARN: Process `Run_LncPipeReporter_without_Design` is defined two or more times
This workflow requires Nextflow version 0.26 or greater -- You are running version 18.10.1

**Comment by likelet** [comment]
sorry for the errors from version check code, this errors comes with the unusual version update of nextflow, and i will fix it by remove the version check version  code 

plz try the latest code with `git clone ` command

**Comment by liuteng-dandiaoliutuo** [comment]
//if( !nextflow.version.matches('0.30+') ) {
//    println print_yellow("This workflow requires Nextflow version 0.26 or greater -- You are running version ")+ print_red(nextflow.version)
//    exit 1
//}

**Comment by liuteng-dandiaoliutuo** [comment]
你应该像这样改，大哥，#不顶用啊

**Comment by liuteng-dandiaoliutuo** [comment]
you should change # to //,  big brother, # is useless

**Comment by likelet** [comment]
sorry for the mistake , i just wrote r code so﹉
 already fixed
