### ISSUE TITLE
when I process the test dataset, error combine_public_annotation

### ISSUE THREAD

**Issue by liuteng-dandiaoliutuo** [likelet/LncPipe#31]
ERROR ~ Error executing process > 'combine_public_annotation (1)'

Caused by:
  Process `combine_public_annotation (1)` terminated with an error exit status (125)

Command executed:

  set -o pipefail
  touch filenames.txt

  perl -lpe 's/ ([^"]\S+) ;/ "$1" ;/g' gencode.chr22.gtf > gencode_annotation_gtf_mod.gtf
  perl -lpe 's/ ([^"]\S+) ;/ "$1" ;/g' lncipedia.chr22.gtf > lncipedia_mod.gtf

  echo  gencode_annotation_gtf_mod.gtf   >>filenames.txt
  echo lncipedia_mod.gtf   >>filenames.txt

  stringtie --merge -o merged_lncRNA.gtf  filenames.txt
  cat gencode_annotation_gtf_mod.gtf   |grep "protein_coding" > gencode_protein_coding.gtf
  gffcompare -r gencode_protein_coding.gtf -p 19 merged_lncRNA.gtf
  awk '$3 =="u"||$3=="x"{print $5}' gffcmp.merged_lncRNA.gtf.tmap |sort|uniq|perl /share/home/guogroup/liut/bin/LncPipe/bin/extract_gtf_by_name.pl merged_lncRNA.gtf - > merged.filter.gtf
  mv  merged.filter.gtf known.lncRNA.gtf

**Comment by liuteng-dandiaoliutuo** [comment]
Command exit status:
  125

Command output:
  (empty)

Command error:
  docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
  See 'docker run --help'.

**Comment by likelet** [comment]
Yes, i saw the error message. Before running the test data, plz make sure the docker server ran properly.  You need to configure  your docker environment first. 
https://forums.docker.com/t/cannot-connect-to-the-docker-daemon-is-the-docker-daemon-running-on-this-host/8925
