### ISSUE TITLE
Predict_coding_abilities_by_CPAT

### ISSUE THREAD

**Issue by liuteng-dandiaoliutuo** [likelet/LncPipe#32]
Dec-11 20:08:32.124 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'Predict_coding_abilities_by_CPAT (1)'

Caused by:
  Process `Predict_coding_abilities_by_CPAT (1)` terminated with an error exit status (1)

Command executed:

  cpat.py -g novel.longRNA.fa                                        -x /usr/bin//dat/Human_Hexamer.tsv                                        -d /usr/bin//dat/Human_logitModel.RData                                        -o novel.longRNA.CPAT.out

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/usr/local/bin/cpat.py", line 4, in <module>
      __import__('pkg_resources').run_script('CPAT==1.2.3', 'cpat.py')
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 661, in run_script
      self.require(requires)[0].run_script(script_name, ns)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1441, in run_script
      exec(code, namespace, namespace)
    File "/usr/local/lib/python2.7/dist-packages/CPAT-1.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/cpat.py", line 244, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/CPAT-1.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/cpat.py", line 195, in main
      for line in open(options.hexamer_dat):
  IOError: [Errno 2] No such file or directory: '/usr/bin//dat/Human_Hexamer.tsv'

**Comment by likelet** [comment]
are u run in a test mode ?
plz specify `--cpatpath /opt/CPAT-1.2.3` (or set `cpatpath ='/opt/CPAT-1.2.3'` in your config file ) when using docker images, otherwise,  set the path to where your cpat installed . 
After that, add  `-resume` in your command to continue analysis without rerun the former steps

**Comment by liuteng-dandiaoliutuo** [comment]
when I run the commad below in the work dir. It works, but not in the nextflow pipeline

cpat.py -g novel.longRNA.fa -x /usr/bin/dat/Human_Hexamer.tsv -d /usr/bin/dat/Human_logitModel.RData -o novel.longRNA.CPAT.out

**Comment by likelet** [comment]
yes it means that you have already cpat installed in your system. you can try modify the all cpay dat file path in `NF` file locally and run once more

**Comment by liuteng-dandiaoliutuo** [comment]
why cpat in Lncpipe.nf is not the one I installed?
I installed cpat 1.2.4 in /usr/bin, but Lncpipe.nf used cpat 1.2.3 version.
I am confused~~

**Comment by likelet** [comment]
are you using the cpat from the docker image?

**Comment by liuteng-dandiaoliutuo** [comment]
yes

**Comment by likelet** [comment]
if you are using cpat from docker image, then it surely  be 1.2.3 version, and set the `cpatpath = '/opt/CPAT-1.2.3'`    which has already be specified in the `docker.config` file. 
BTW, in the latest version of LncPipe (v 2.4.3 ), this parameter has already been deprecated as  i have moved the model file into `bin` folder of the  pipe.

**Comment by liuteng-dandiaoliutuo** [comment]
Thanks!
