### ISSUE TITLE
Processing Test Data as well as Local Data ERROR

### ISSUE THREAD

**Issue by IrenaeusChan** [likelet/LncPipe#38]
Hello,

I've been trying to get this pipeline running on my machine. When trying to run this pipeline for MOUSE samples, I am encountering the same issue as user: brunohhomem on the other ISSUE thread. When running this pipeline on HUMAN samples and the TEST DATA I am encountering this issue during the: "Quantification by Kallisto in Paired End Mode"

```
quantification by kallisto in paired end mode
[74/5c54b0] Submitted process > Run_kallisto_for_quantification (R1126N)
[6e/469682] Submitted process > Get_kallisto_matrix (Kallisto)
ERROR ~ Error executing process > 'Get_kallisto_matrix (Kallisto)'

Caused by:
  Process `Get_kallisto_matrix (Kallisto)` terminated with an error exit status (1)

Command executed:

  perl /mnt/tank/bench/scripts/LncPipe/bin/get_map_table.pl  --gtf_file=final_all.gtf  > map.file
  R CMD BATCH /mnt/tank/bench/scripts/LncPipe/bin/get_kallisto_matrix.R

Command exit status:
  1

Command output:
  (empty)

The get_kallisto_matrix.Rout file shows the error as:
> fwrite(trans.kallisto.count.merge ,file="kallisto.count.txt",sep="\t",quote=F,row.names=F)
Error in fwrite(trans.kallisto.count.merge, file = "kallisto.count.txt",  : 
  is.list(x) is not TRUE
Calls: fwrite -> stopifnot
Execution halted
```

I am currently using the Docker with these settings (Everything not displayed is default):
```fastq_ext = '*_{R1,R2}_001.fastq.gz'
fasta_ref = '/mnt/tank/bench/data/GRCh38.primary_assembly.genome.fa'
design = null
hisat2_index = '/mnt/tank/bench/data/HISAT_INDEX_HG38_GENOME/'
gencode_annotation_gtf = "/mnt/tank/bench/data/gencode.v29.annotation.gtf"
lncipedia_gtf = "/mnt/tank/bench/data/gencode.v29.long_noncoding_RNAs.gtf"
```

**Comment by brunohhomem** [comment]
> Hello,
> 
> I've been trying to get this pipeline running on my machine. When trying to run this pipeline for MOUSE samples, I am encountering the same issue as user: brunohhomem on the other ISSUE thread. When running this pipeline on HUMAN samples and the TEST DATA I am encountering this issue during the: "Quantification by Kallisto in Paired End Mode"
> 
> ```
> quantification by kallisto in paired end mode
> [74/5c54b0] Submitted process > Run_kallisto_for_quantification (R1126N)
> [6e/469682] Submitted process > Get_kallisto_matrix (Kallisto)
> ERROR ~ Error executing process > 'Get_kallisto_matrix (Kallisto)'
> 
> Caused by:
>   Process `Get_kallisto_matrix (Kallisto)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   perl /mnt/tank/bench/scripts/LncPipe/bin/get_map_table.pl  --gtf_file=final_all.gtf  > map.file
>   R CMD BATCH /mnt/tank/bench/scripts/LncPipe/bin/get_kallisto_matrix.R
> 
> Command exit status:
>   1
> 
> Command output:
>   (empty)
> 
> The get_kallisto_matrix.Rout file shows the error as:
> > fwrite(trans.kallisto.count.merge ,file="kallisto.count.txt",sep="\t",quote=F,row.names=F)
> Error in fwrite(trans.kallisto.count.merge, file = "kallisto.count.txt",  : 
>   is.list(x) is not TRUE
> Calls: fwrite -> stopifnot
> Execution halted
> ```
> I am currently using the Docker with these settings (Everything not displayed is default):
> 
> ```
> fasta_ref = '/mnt/tank/bench/data/GRCh38.primary_assembly.genome.fa'
> design = null
> hisat2_index = '/mnt/tank/bench/data/HISAT_INDEX_HG38_GENOME/'
> gencode_annotation_gtf = "/mnt/tank/bench/data/gencode.v29.annotation.gtf"
> lncipedia_gtf = "/mnt/tank/bench/data/gencode.v29.long_noncoding_RNAs.gtf"
> ```

The kallisto error is very common when the machine can't handle with the process. I think that your machine can't do the analisys from kallisto. This error appear when I try to run any data from human with pipe, in TESTDATA the pipe runs normally.
For mouse data I don't have news.

**Comment by brunohhomem** [comment]
I think you can try to run Kallisto process throught galaxy

**Comment by IrenaeusChan** [comment]
> I think you can try to run Kallisto process throught galaxy

So you're saying the Docker computer cannot handle the kallisto process? If that is true, how to run it through Galaxy? Or should I just download the dependencies and process the samples locally?

**Comment by brunohhomem** [comment]
> > I think you can try to run Kallisto process throught galaxy
> 
> So you're saying the Docker computer cannot handle the kallisto process? If that is true, how to run it through Galaxy? Or should I just download the dependencies and process the samples locally?

No, I'm saying that in my case, when I try to use Human data, the kallisto error appears. And this is because my server don't have enough resources. The docker only give you all the programs and dependencies. The docker isn't the issue.
When I put the TESTDATA the process run to the end, because the TESTDATA are smaller than the complete human data.
Galaxy is a WebServer, so if your computer/server can't handle with kallisto process, maybe you can put the files there and try to get the kallisto analisis.

**Comment by likelet** [comment]
hi guys, a possible solution for this is that to reduce the parallel run forks for your situation. 
to do this, you should modify the process configuration in `docker.config` file 
```groovy 
process {
    withLabel: para {
        maxForks = 6
    }

    withLabel: 'qc' {
        maxForks = 6
    }

}
```
plz change the `maxForks` number into 4 or less to see whether it works for you to go through the Kallisto. 
BTW, add the `-resume ` parameter in your command can skip running the steps that already done.

**Comment by likelet** [comment]
> Hello,
> 
> I've been trying to get this pipeline running on my machine. When trying to run this pipeline for MOUSE samples, I am encountering the same issue as user: brunohhomem on the other ISSUE thread. When running this pipeline on HUMAN samples and the TEST DATA I am encountering this issue during the: "Quantification by Kallisto in Paired End Mode"
> 
> ```
> quantification by kallisto in paired end mode
> [74/5c54b0] Submitted process > Run_kallisto_for_quantification (R1126N)
> [6e/469682] Submitted process > Get_kallisto_matrix (Kallisto)
> ERROR ~ Error executing process > 'Get_kallisto_matrix (Kallisto)'
> 
> Caused by:
>   Process `Get_kallisto_matrix (Kallisto)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   perl /mnt/tank/bench/scripts/LncPipe/bin/get_map_table.pl  --gtf_file=final_all.gtf  > map.file
>   R CMD BATCH /mnt/tank/bench/scripts/LncPipe/bin/get_kallisto_matrix.R
> 
> Command exit status:
>   1
> 
> Command output:
>   (empty)
> 
> The get_kallisto_matrix.Rout file shows the error as:
> > fwrite(trans.kallisto.count.merge ,file="kallisto.count.txt",sep="\t",quote=F,row.names=F)
> Error in fwrite(trans.kallisto.count.merge, file = "kallisto.count.txt",  : 
>   is.list(x) is not TRUE
> Calls: fwrite -> stopifnot
> Execution halted
> ```
> I am currently using the Docker with these settings (Everything not displayed is default):
> 
> ```
> fasta_ref = '/mnt/tank/bench/data/GRCh38.primary_assembly.genome.fa'
> design = null
> hisat2_index = '/mnt/tank/bench/data/HISAT_INDEX_HG38_GENOME/'
> gencode_annotation_gtf = "/mnt/tank/bench/data/gencode.v29.annotation.gtf"
> lncipedia_gtf = "/mnt/tank/bench/data/gencode.v29.long_noncoding_RNAs.gtf"
> ```
i checked the log, it should be an error from the `collapse matrix ` step. 
could you plz send the file under the `work/6e/469682*` to me by mail "zhaoqi@sysucc.org.cn" (cp the file and compressed it, plz make sure that you have send the hard file  rather than links)

**Comment by IrenaeusChan** [comment]
I am currently running a single sample to verify and explore the results. My main dataset is Mouse, but the issue noted before is still unresolved. However, I have a single human test data set that I am using to verify the viability of this pipeline.


If the output and results are good I will be adding this pipeline to our main project with 14 samples.

**Comment by likelet** [comment]
well, you can try it from at least 2 samples. Otherwise, it will stop at merge sample step.

**Comment by brunohhomem** [comment]
> hi guys, a possible solution for this is that to reduce the parallel run forks for your situation.
> to do this, you should modify the process configuration in `docker.config` file
> 
> ```groovy
> process {
>     withLabel: para {
>         maxForks = 6
>     }
> 
>     withLabel: 'qc' {
>         maxForks = 6
>     }
> 
> }
> ```
> 
> plz change the `maxForks` number into 4 or less to see whether it works for you to go through the Kallisto.
> BTW, add the `-resume ` parameter in your command can skip running the steps that already done.

I've already tried that. Multiple tests on qc and para. Didn't worked.

**Comment by likelet** [comment]
In regard to running it for mouse data, we are now working at a local test with the latest nextflow version.  Some code will be modified and will notify you once it comes out (maybe a few days).

**Comment by brunohhomem** [comment]
I searched for the qc and para on the latest commit and don't have these paramns anymore. After some updates, the pipe lost the **docker.config**, and now have only _nextflow.config_, and this config file don't have these paramns. _Main.nf_ doesn't have either.

**Comment by IrenaeusChan** [comment]
> well, you can try it from at least 2 samples. Otherwise, it will stop at merge sample step.

This solved my issue regarding the Kallisto Quantification. A new issue appeared afterwards during the edger process in "Run_LncPipeReporter_without_Design"

However, I just needed the lincRNA counts generated from Kallisto which is found under Reports.

> In regard to running it for mouse data, we are now working at a local test with the latest nextflow version. Some code will be modified and will notify you once it comes out (maybe a few days).

When the Mouse version is released, please do notify us.

Thank you.
