### ISSUE TITLE
Fastp error

### ISSUE THREAD

**Issue by yzh37545** [likelet/LncPipe#39]
I tried the scripts on Mouse data. But got an error for fastp command. The error is 

![image](https://user-images.githubusercontent.com/39535598/55436178-3885eb00-5561-11e9-913d-7639387f0c02.png)

Is it caused by my data Mouse19 or fastp installation? It looks like that other samples are good.

Thank you!

**Comment by likelet** [comment]
Hi Yu Zhu
seems that fastp was not well installed in your local server.  Maybe you should use the docker instead, which prepared all tools and dependencies required by LncPipe
Qi

**Comment by yzh37545** [comment]
Hi, Dr. Zhao,

Should I also revise the docker.config like nextflow.config based on
non-human samples?

Thank you!

Best,
Yu

**Comment by likelet** [comment]
you can refer this in your config file, which  I tested the mouse data locally:
```groovy 
params {
/*
    User setting options (mandatory)
 */
// input file and genome reference

    fastq_ext = '0.data/*.fq.gz'
    fasta_ref = 'genome/chr18.fa'
    design = 'design.file' // or null
    hisat2_index = 'genome/hisat2.chr18'
    cpatpath='/opt/CPAT-1.2.3'

/*
    User setting options (optional)
     */
    // tools setting
    hisat_strand = 'RF'

    star_index = ''//set if star used
    bowtie2_index = ''//set if tophat used
    aligner = "hisat" // or "star","tophat"
    sam_processor="sambamba"//or "samtools(deprecated)"
    qctools ="fastp"  // or "afterqc","fastp","fastqc","none" to skip qc step
    detools = "edger"//or "deseq2"
    quant = "kallisto"// or 'htseq'
    //other setting
    singleEnd = true
    unstrand = false
    skip_combine = false
    lncRep_Output = 'reporter.html'
    lncRep_theme = 'npg'
    lncRep_cdf_percent = 10
    lncRep_max_lnc_len = 10000
    lncRep_min_expressed_sample = 50
    mem=60
    cpu=30

 /*
    for non-human setting
 */
    species="mouse"// mouse , zebrafish, fly
    known_coding_gtf="genome/chr18_protein_coding.gtf"
    known_lncRNA_gtf="genome/chr18_lncRNA.gtf"


/*
Don't modify
*/
    cpatpath ='/opt/CPAT-1.2.3'


}

/*
Don't modify either
*/
// Docker options
docker.runOptions = '-u $(id -u):$(id -g)'
docker.enabled = true
process.container = 'bioinformatist/lncpipe:latest'

//process.executor="pbs"
// individual process setting
process.cache = 'deep'

process {
    withLabel: para {
        maxForks = 6
    }

    withLabel: 'qc' {
        maxForks = 6
    }

}

manifest {
    homePage = 'https//github.com/likelet/LncPipe'
    description = 'LncPipe:a Nextflow-based Long non-coding RNA analysis PIPELINE'
    mainScript = 'LncRNAanalysisPipe.nf'
}

```

**Comment by yzh37545** [comment]
Hi, 
Thanks for your quick response. Since the cluster of my college doesn't allow docker installation, I tried to use singularity instead. But when I build the image, several errors pump out, like this. Do you have any suggestions? I am new to this field. Thanks a lot for your help! 
![image](https://user-images.githubusercontent.com/39535598/55510767-94fe0e80-5624-11e9-9d92-dcc3a17b4132.png)

**Comment by yzh37545** [comment]
Hi, Dr. Zhao,

I try to install Dependencies for LncPipe. But when I install CPAT
<http://rna-cpat.sourceforge.net/>:Citation
<https://academic.oup.com/nar/article/41/6/e74/2902455/CPAT-Coding-Potential-Assessment-Tool-using-an>.
There is a command mv dat/* /LncPipeDB/. Where should LncPipeDB be? There
is no such folder in LncPipe. Should it be created as /root/LncPipeDB/?

Thank you so much!

Best,
Yu

**Comment by likelet** [comment]
update already, users do not need this configuration anymore.

**Comment by brunohhomem** [comment]
Hi how are you guys?
I'm having a similar problem as @yzh37545 , when the pipeline execution stop at "fastq_hisat2_aligment_For_discovery".
My data is from mouse (6 set), all reference files are new and recently downloaded. I'm using DOCKER, and the lastest nextflow version also the latest git from lncpipe repositories.
I'll attach a print screen and the nextflow log for reviewning.
![image](https://user-images.githubusercontent.com/43353129/62070049-10a54c00-b210-11e9-95b3-1ca4873be55d.png)
[next1.log](https://github.com/likelet/LncPipe/files/3443612/next1.log)

My docker config is similar to config of @likelet above (attached too).

[docker.txt](https://github.com/likelet/LncPipe/files/3443616/docker.txt)
