### ISSUE TITLE
Version Dependencies

### ISSUE THREAD

**Issue by maflister** [likelet/LncPipe#40]
Are the exact package versions in environment.yml required? As an example, your install instruction for gffcompare recommends downloading the master.zip which will default to the latest version possible from GitHub, and not your stated dependency of version 0.10.1. Please advise.

**Comment by likelet** [comment]
sorry for not specify it clearly, we have run it stable on  0.10.1 of gffcompare. Thanks for pointing out this issue and you will find it in the `conda` install configuration: `environment.yml` file

**Comment by maflister** [comment]
Unfortunately version 0.10.1 of gffcompare is no longer available from conda, as far as I can tell.

**Comment by likelet** [comment]
well, thanks for reminding me of this, I will update it ASAP:)
Actually, we set the exact package version in environment.yml cause the exact version of dependencies has been tested locally. We expected the users can produce the exact same analysis result when using the same data.
