### ISSUE TITLE
Nextflow version 0.26 Installation

### ISSUE THREAD

**Issue by Behnaz64** [likelet/LncPipe#45]
Hi everyone

I'm trying to run LncPipe, but I receive this message: "This workflow requires Nextflow version 0.26 or greater -- You are running version 20.01.0"

I have tried two commands to install Nextflow on my system: wget -qO- https://get.nextflow.io | bash AND curl -fsSL get.nextflow.io | bash

Both of them install version 20.01.0. What should I do to get version 0.26?

Thank you for your help

**Comment by likelet** [comment]
This is a warning, not an error in this case(ignoring this if no error throws). Nextflow has two version systems during its development.

**Comment by Behnaz64** [comment]
Thank you for your response. I receive a long error message when I try to run the pipeline for test data. I will copy the message in another post

**Comment by likelet** [comment]
ok plz post the error message here.

**Comment by likelet** [comment]
close cause another issue opened

**Comment by bioinformatist** [comment]
@likelet 666!
