### ISSUE TITLE
Error in running LncPipeTestData

### ISSUE THREAD

**Issue by Behnaz64** [likelet/LncPipe#46]
Hello

I'm trying to run LncPipe for the provided test data. Here is the command I run:

nextflow -c docker.config run ~/LncPipe/LncRNAanalysisPipe.nf --max_cpus 1 -with-trace -resume -with-timeline timeline.html

and here is the error message I receive; could you please have a look and let me know why this happens?:

NOTE: Nextflow is not tested with Java 13.0.2 -- It's recommended the use of version 8 up to 12

N E X T F L O W  ~  version 20.01.0
Launching `/Users/my_username/LncPipe/LncRNAanalysisPipe.nf` [naughty_meninsky] - revision: 32d1fd7240
This workflow requires Nextflow version 0.26 or greater -- You are running version 20.01.0
[35mYou are running LncPipe with the following parameters:
[35mChecking parameters ...
[33m=====================================
[33mSpecies:                        human
[33mFastq file extension:           Fastq/*_{1,2}.fq.gz
[33mSingle end :                    false
[33mskip annotation process:        false
[33mInput folder:                   ./
[33mOutput folder:                  ./
[33mGenome sequence location:       ./Genome/chrX.fa
[33mSTAR index path:                
[33mHISAT2 index path:               ./Genome/hisat2Index/chrX
[33mbowtie/tophat index path:       
[33mGENCODE annotation location:    ./Genome/gencode.v25.annotation.chrX.gtf
[33mlncipedia annotation location:  ./Genome/lncipedia_4_0.chrX.gtf
[33m=====================================

Exceeding the max available processors, 
 use default parameter to run pipe. Combining known annotations from GTFs
Analysis from fastq file
Perform quality control of raw fastq files 
executor >  local (2)
[fa/45fa39] process > combine_public_annotation      [  0%] 0 of 1
[bb/fbeb3b] process > Run_FastP                      [  0%] 0 of 2
[-        ] process > fastq_hisat2_alignment_For_... -
[-        ] process > StringTie_assembly             -
[-        ] process > StringTie_merge_assembled_gtf  -
[-        ] process > Merge_assembled_gtf_with_GE... -
[-        ] process > Identify_novel_lncRNA_with_... -
[-        ] process > Predict_coding_abilities_by... -
[-        ] process > Predict_coding_abilities_by... -
[-        ] process > Filter_lncRNA_by_coding_pot... -
[-        ] process > Summary_renaming_and_classi... -
[-        ] process > Rerun_CPAT_to_evaluate_lncRNA  -
[-        ] process > Rerun_CPAT_to_evaluate_coding  -
[-        ] process > Secondary_basic_statistic      -
[-        ] process > Build_kallisto_index_of_GTF... -
[-        ] process > Run_kallisto_for_quantifica... -
[-        ] process > Get_kallisto_matrix            -
[-        ] process > Run_LncPipeReporter            -
Error executing process > 'combine_public_annotation (1)'

Caused by:
  Process `combine_public_annotation (1)` terminated with an error exit status (125)

Command executed:

  set -o pipefail
  touch filenames.txt
  
  perl -lpe 's/ ([^"]\S+) ;/ "$1" ;/g' gencode.v25.annotation.chrX.gtf > gencode_annotation_gtf_mod.gtf
  perl -lpe 's/ ([^"]\S+) ;/ "$1" ;/g' lncipedia_4_0.chrX.gtf > lncipedia_mod.gtf
  
  echo  gencode_annotation_gtf_mod.gtf   >>filenames.txt
  echo lncipedia_mod.gtf   >>filenames.txt
  
  stringtie --merge -o merged_lncRNA.gtf  filenames.txt
  cat gencode_annotation_gtf_mod.gtf   |grep "protein_coding" > gencode_protein_coding.gtf
  gffcompare -r gencode_protein_coding.gtf -p 3 merged_lncRNA.gtf
  awk '$3 =="u"||$3=="x"{print $5}' gffcmp.merged_lncRNA.gtf.tmap |sort|uniq|perl /Users/behnazkhavari/LncPipe/bin/extract_gtf_by_name.pl merged_lncRNA.gtf - > merged.filter.gtf
executor >  local (3)
[fa/45fa39] process > combine_public_annotation      [100%] 1 of 1, failed: 1 ✘
[82/5f5597] process > Run_FastP                      [  0%] 0 of 2
[-        ] process > fastq_hisat2_alignment_For_... -
[-        ] process > StringTie_assembly             -
[-        ] process > StringTie_merge_assembled_gtf  -
[-        ] process > Merge_assembled_gtf_with_GE... -
[-        ] process > Identify_novel_lncRNA_with_... -
[-        ] process > Predict_coding_abilities_by... -
[-        ] process > Predict_coding_abilities_by... -
[-        ] process > Filter_lncRNA_by_coding_pot... -
[-        ] process > Summary_renaming_and_classi... -
[-        ] process > Rerun_CPAT_to_evaluate_lncRNA  -
[-        ] process > Rerun_CPAT_to_evaluate_coding  -
[-        ] process > Secondary_basic_statistic      -
[-        ] process > Build_kallisto_index_of_GTF... -
[-        ] process > Run_kallisto_for_quantifica... -
[-        ] process > Get_kallisto_matrix            -
[-        ] process > Run_LncPipeReporter            -
WARN: Killing pending tasks (2)
Error executing process > 'combine_public_annotation (1)'

Caused by:
  Process `combine_public_annotation (1)` terminated with an error exit status (125)

Command executed:

  set -o pipefail
  touch filenames.txt
  
  perl -lpe 's/ ([^"]\S+) ;/ "$1" ;/g' gencode.v25.annotation.chrX.gtf > gencode_annotation_gtf_mod.gtf
  perl -lpe 's/ ([^"]\S+) ;/ "$1" ;/g' lncipedia_4_0.chrX.gtf > lncipedia_mod.gtf
  
  echo  gencode_annotation_gtf_mod.gtf   >>filenames.txt
  echo lncipedia_mod.gtf   >>filenames.txt
  
  stringtie --merge -o merged_lncRNA.gtf  filenames.txt
  cat gencode_annotation_gtf_mod.gtf   |grep "protein_coding" > gencode_protein_coding.gtf
executor >  local (3)
[fa/45fa39] process > combine_public_annotation      [100%] 1 of 1, failed: 1 ✘
[82/5f5597] process > Run_FastP                      [  0%] 0 of 3
[-        ] process > fastq_hisat2_alignment_For_... -
[-        ] process > StringTie_assembly             -
[-        ] process > StringTie_merge_assembled_gtf  -
[-        ] process > Merge_assembled_gtf_with_GE... -
[-        ] process > Identify_novel_lncRNA_with_... -
[-        ] process > Predict_coding_abilities_by... -
[-        ] process > Predict_coding_abilities_by... -
[-        ] process > Filter_lncRNA_by_coding_pot... -
[-        ] process > Summary_renaming_and_classi... -
[-        ] process > Rerun_CPAT_to_evaluate_lncRNA  -
[-        ] process > Rerun_CPAT_to_evaluate_coding  -
[-        ] process > Secondary_basic_statistic      -
[-        ] process > Build_kallisto_index_of_GTF... -
[-        ] process > Run_kallisto_for_quantifica... -
[-        ] process > Get_kallisto_matrix            -
[-        ] process > Run_LncPipeReporter            -
WARN: Killing pending tasks (2)
Error executing process > 'combine_public_annotation (1)'

Caused by:
  Process `combine_public_annotation (1)` terminated with an error exit status (125)

Command executed:

  set -o pipefail
  touch filenames.txt
  
  perl -lpe 's/ ([^"]\S+) ;/ "$1" ;/g' gencode.v25.annotation.chrX.gtf > gencode_annotation_gtf_mod.gtf
  perl -lpe 's/ ([^"]\S+) ;/ "$1" ;/g' lncipedia_4_0.chrX.gtf > lncipedia_mod.gtf
  
  echo  gencode_annotation_gtf_mod.gtf   >>filenames.txt
  echo lncipedia_mod.gtf   >>filenames.txt
  
  stringtie --merge -o merged_lncRNA.gtf  filenames.txt
  cat gencode_annotation_gtf_mod.gtf   |grep "protein_coding" > gencode_protein_coding.gtf
executor >  local (3)
[fa/45fa39] process > combine_public_annotation      [100%] 1 of 1, failed: 1 ✘
[82/5f5597] process > Run_FastP                      [  0%] 0 of 4
[-        ] process > fastq_hisat2_alignment_For_... -
[-        ] process > StringTie_assembly             -
[-        ] process > StringTie_merge_assembled_gtf  -
[-        ] process > Merge_assembled_gtf_with_GE... -
[-        ] process > Identify_novel_lncRNA_with_... -
[-        ] process > Predict_coding_abilities_by... -
[-        ] process > Predict_coding_abilities_by... -
[-        ] process > Filter_lncRNA_by_coding_pot... -
[-        ] process > Summary_renaming_and_classi... -
[-        ] process > Rerun_CPAT_to_evaluate_lncRNA  -
[-        ] process > Rerun_CPAT_to_evaluate_coding  -
[-        ] process > Secondary_basic_statistic      -
[-        ] process > Build_kallisto_index_of_GTF... -
[-        ] process > Run_kallisto_for_quantifica... -
[-        ] process > Get_kallisto_matrix            -
[-        ] process > Run_LncPipeReporter            -
WARN: Killing pending tasks (2)
Error executing process > 'combine_public_annotation (1)'

Caused by:
  Process `combine_public_annotation (1)` terminated with an error exit status (125)

Command executed:

  set -o pipefail
  touch filenames.txt
  
  perl -lpe 's/ ([^"]\S+) ;/ "$1" ;/g' gencode.v25.annotation.chrX.gtf > gencode_annotation_gtf_mod.gtf
  perl -lpe 's/ ([^"]\S+) ;/ "$1" ;/g' lncipedia_4_0.chrX.gtf > lncipedia_mod.gtf
  
  echo  gencode_annotation_gtf_mod.gtf   >>filenames.txt
  echo lncipedia_mod.gtf   >>filenames.txt
  
  stringtie --merge -o merged_lncRNA.gtf  filenames.txt
  cat gencode_annotation_gtf_mod.gtf   |grep "protein_coding" > gencode_protein_coding.gtf
  gffcompare -r gencode_protein_coding.gtf -p 3 merged_lncRNA.gtf
  awk '$3 =="u"||$3=="x"{print $5}' gffcmp.merged_lncRNA.gtf.tmap |sort|uniq|perl /Users/behnazkhavari/LncPipe/bin/extract_gtf_by_name.pl merged_lncRNA.gtf - > merged.filter.gtf
  mv  merged.filter.gtf known.lncRNA.gtf

Command exit status:
  125

Command output:
  (empty)

Command error:
  docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
  See 'docker run --help'.

Work dir:
  /Users/username/LncPipeTestData/work/fa/45fa39790e215c2d4da19dc648bc53

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by likelet** [comment]
well i will check this with the latest nextflow, thanks for the post

**Comment by likelet** [comment]
Sorry, I did not notice that, seems your docker was not run properly,  plz configure your docker first 

Install with the Docker Installation Script

Start Docker: `sudo service docker start`
Verify Docker:` sudo docker run hello-world `

 and here is the post configuration of your docker 

https://docs.docker.com/install/linux/linux-postinstall/
