### ISSUE TITLE
Fail to download the test data

### ISSUE THREAD

**Issue by Meimei2** [likelet/LncPipe#48]
Hello,
I found that I failed to download the testdata from the link you provided either derectly through Google Chrome or using wget command on linux. Maybe there are something wrong, hope that you can check and update the link. Error information is as follows:
wget -c http://cancerbio.info/pub/LncPipeTestData.tar.gz
--2020-06-06 15:17:31-- http://cancerbio.info/pub/LncPipeTestData.tar.gz
Resolving cancerbio.info (cancerbio.info)... failed: No address associated with hostname.
wget: unable to resolve host address ‘cancerbio.info’
Thanks for your help!

**Comment by likelet** [comment]
Hi meimei  
Thanks for using LncPipe. I checked the link of the test data. Seems the link is out of work right now.  So I remove the old URL and add a new one here. 
You can access the test data with the following link.
http://omicsbio.info/pub/testdata.tar.gz 
thanks for this issue to bring the error to our sight. 
Qi
