### ISSUE TITLE
Error executing process > 'Run_LncPipeReporter (Generating report ...)'>duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by bihuaf** [likelet/LncPipe#49]
LncRNAanalysisPipe was performed using your test data, but It can not be completed.

N E X T F L O W  ~  version 20.04.1
Launching `LncRNAanalysisPipe.nf` [prickly_poitras] - revision: 32d1fd7240
This workflow requires Nextflow version 0.26 or greater -- You are running version 20.04.1
[35mYou are running LncPipe with the following parameters:
[35mChecking parameters ...
[33m=====================================
[33mSpecies:                        human
[33mFastq file extension:           Fastq/*{1,2}.fastq.gz
[33mSingle end :                    false
[33mskip annotation process:        false
[33mInput folder:                   ./
[33mOutput folder:                  ./
[33mGenome sequence location:       Genome/chr22.fa
[33mSTAR index path:                
[33mHISAT2 index path:               Genome/hisat_index/*.ht2
[33mbowtie/tophat index path:       
[33mGENCODE annotation location:    Genome/gencode.chr22.gtf
[33mlncipedia annotation location:  Genome/lncipedia.chr22.gtf
[33m=====================================

Combining known annotations from GTFs
Analysis from fastq file
Perform quality control of raw fastq files 
[-        ] process > combine_public_annotation      -
[-        ] process > combine_public_annotation      [  0%] 0 of 1
[-        ] process > Run_FastP                      -
[-        ] process > fastq_hisat2_alignment_For_... -
[-        ] process > StringTie_assembly             -
executor >  local (2)
[98/4f5f6c] process > combine_public_annotation (1)  [100%] 1 of 1 ✔
[24/1e240c] process > Run_FastP (uPDLSCs1)           [  0%] 0 of 4
executor >  local (3)
[98/4f5f6c] process > combine_public_annotation (1)  [100%] 1 of 1 ✔
[24/1e240c] process > Run_FastP (uPDLSCs1)           [ 25%] 1 of 4
executor >  local (4)
[98/4f5f6c] process > combine_public_annotation (1)  [100%] 1 of 1 ✔
executor >  local (5)
executor >  local (5)
[98/4f5f6c] process > combine_public_annotation (1)  [100%] 1 of 1 ✔
executor >  local (6)
executor >  local (6)
executor >  local (8)
executor >  local (8)
executor >  local (10)
executor >  local (13)
executor >  local (14)
   ### ERROR ###   Max cpus '[:]' is not valid! Using default value: 8
executor >  local (16)
[98/4f5f6c] process > combine_public_annotation (1)  [100%] 1 of 1 ✔
executor >  local (18)
executor >  local (19)
executor >  local (20)
[98/4f5f6c] process > combine_public_annotation (1)  [100%] 1 of 1 ✔
[8f/7c0b7e] process > Run_FastP (dPDLSCs1)           [100%] 4 of 4 ✔
executor >  local (22)
[98/4f5f6c] process > combine_public_annotation (1)  [100%] 1 of 1 ✔
[8f/7c0b7e] process > Run_FastP (dPDLSCs1)           [100%] 4 of 4 ✔
[e9/d0bd78] process > fastq_hisat2_alignment_For_... [100%] 4 of 4 ✔
[3e/b31271] process > StringTie_assembly (dPDLSCs1)  [100%] 4 of 4 ✔
[af/d8fbc5] process > StringTie_merge_assembled_g... [100%] 1 of 1 ✔
[c7/2b8927] process > Merge_assembled_gtf_with_GE... [100%] 1 of 1 ✔
[42/35b7df] process > Identify_novel_lncRNA_with_... [100%] 1 of 1 ✔
executor >  local (23)
executor >  local (27)
executor >  local (29)
executor >  local (30)
[98/4f5f6c] process > combine_public_annotation (1)  [100%] 1 of 1 ✔
[8f/7c0b7e] process > Run_FastP (dPDLSCs1)           [100%] 4 of 4 ✔
[e9/d0bd78] process > fastq_hisat2_alignment_For_... [100%] 4 of 4 ✔
[3e/b31271] process > StringTie_assembly (dPDLSCs1)  [100%] 4 of 4 ✔
[af/d8fbc5] process > StringTie_merge_assembled_g... [100%] 1 of 1 ✔
[c7/2b8927] process > Merge_assembled_gtf_with_GE... [100%] 1 of 1 ✔
[42/35b7df] process > Identify_novel_lncRNA_with_... [100%] 1 of 1 ✔
[70/f7a69a] process > Predict_coding_abilities_by... [100%] 1 of 1 ✔
[34/ce3f0b] process > Predict_coding_abilities_by... [100%] 1 of 1 ✔
[44/794ba5] process > Filter_lncRNA_by_coding_pot... [100%] 1 of 1 ✔
[6c/ed2818] process > Summary_renaming_and_classi... [100%] 1 of 1 ✔
[89/3136d0] process > Rerun_CPAT_to_evaluate_lncR... [100%] 1 of 1 ✔
[92/7e9c39] process > Rerun_CPAT_to_evaluate_codi... [100%] 1 of 1 ✔
[cb/109152] process > Secondary_basic_statistic (1)  [100%] 1 of 1 ✔
[15/c3bacb] process > Build_kallisto_index_of_GTF... [100%] 1 of 1 ✔
[d6/465f86] process > Run_kallisto_for_quantifica... [100%] 4 of 4 ✔
[f6/9dd13d] process > Get_kallisto_matrix (Kallisto) [100%] 1 of 1 ✔
[9a/da60f7] process > Run_LncPipeReporter (Genera... [  0%] 0 of 1
Error executing process > 'Run_LncPipeReporter (Generating report ...)'

Caused by:
  Process `Run_LncPipeReporter (Generating report ...)` terminated with an error exit status (1)

Command executed:

  perl /home/skyhorse/Desktop/lncpipe/LncPipe/bin/modifyDesign.pl design.file  > design.matrix 
  Rscript -e "library(LncPipeReporter);run_reporter(input='.', output = 'reporter.html',output_dir='./LncPipeReports',de.method='edger',theme = 'npg',cdf.percent = 10,max.lncrna.len = 10000,min.expressed.sample = 50, ask = FALSE)"

Command exit status:
  1

Command output:
    ordinary text without R code
  
  
    |                                                                       
    |..............................................................   |  95%
  label: lncRNA table
  
    |                                                                       
    |.................................................................| 100%
    ordinary text without R code
  
  
  
    |                                                                       
    |.............................................................    |  94%
    ordinary text without R code
  
  
    |                                                                       
    |.................................................................| 100%
  label: DE-child (with options) 
  List of 2
   $ child: language switch(de.method, edger = "edger.Rmd", deseq2 = "deseq2.Rmd", noiseq = "noiseq.Rmd")
   $ eval : language !is.null(type.list[["Design"]])
  
  
    |                                                                       
    |                                                                 |   0%
    |                                                                       
    |...                                                              |   5%
    ordinary text without R code
  
  
    |                                                                       
    |......                                                           |  10%
  label: setup (with options) 
  List of 1
   $ include: logi FALSE
  
  
    |                                                                       
    |..........                                                       |  15%
    ordinary text without R code
  
  
    |                                                                       
    |.............                                                    |  20%
  label: unnamed-chunk-11
  

Command error:
  
  
  processing file: reporter.Rmd
  
  
  processing file: ./Hisat2.Rmd
  
  
  processing file: ./lncRNA.Rmd
  
  
  processing file: ./edger.Rmd
  Quitting from lines 9-57 (./edger.Rmd) 
  Quitting from lines 250-255 (./edger.Rmd) 
  Error in `.rowNamesDF<-`(x, value = value) : 
    duplicate 'row.names' are not allowed
  Calls: run_reporter ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
  In addition: Warning messages:
  1: In eval(expr, envir, enclos) : NAs introduced by coercion
  2: non-unique values when setting 'row.names':  
  Execution halted

Work dir:
  /home/skyhorse/Desktop/lncpipe/LncPipe/work/9a/da60f7a01eefad36c0f8ef5880ceb5

Tip: you can try to figure out what's wrong by changing to the process work dir executor >  local (30)
[98/4f5f6c] process > combine_public_annotation (1)  [100%] 1 of 1 ✔
[8f/7c0b7e] process > Run_FastP (dPDLSCs1)           [100%] 4 of 4 ✔
[e9/d0bd78] process > fastq_hisat2_alignment_For_... [100%] 4 of 4 ✔
[3e/b31271] process > StringTie_assembly (dPDLSCs1)  [100%] 4 of 4 ✔
[af/d8fbc5] process > StringTie_merge_assembled_g... [100%] 1 of 1 ✔
[c7/2b8927] process > Merge_assembled_gtf_with_GE... [100%] 1 of 1 ✔
[42/35b7df] process > Identify_novel_lncRNA_with_... [100%] 1 of 1 ✔
[70/f7a69a] process > Predict_coding_abilities_by... [100%] 1 of 1 ✔
[34/ce3f0b] process > Predict_coding_abilities_by... [100%] 1 of 1 ✔
[44/794ba5] process > Filter_lncRNA_by_coding_pot... [100%] 1 of 1 ✔
[6c/ed2818] process > Summary_renaming_and_classi... [100%] 1 of 1 ✔
[89/3136d0] process > Rerun_CPAT_to_evaluate_lncR... [100%] 1 of 1 ✔
[92/7e9c39] process > Rerun_CPAT_to_evaluate_codi... [100%] 1 of 1 ✔
[cb/109152] process > Secondary_basic_statistic (1)  [100%] 1 of 1 ✔
[15/c3bacb] process > Build_kallisto_index_of_GTF... [100%] 1 of 1 ✔
[d6/465f86] process > Run_kallisto_for_quantifica... [100%] 4 of 4 ✔
[f6/9dd13d] process > Get_kallisto_matrix (Kallisto) [100%] 1 of 1 ✔
[9a/da60f7] process > Run_LncPipeReporter (Genera... [100%] 1 of 1, failed: 1 ✘
Error executing process > 'Run_LncPipeReporter (Generating report ...)'

Caused by:
  Process `Run_LncPipeReporter (Generating report ...)` terminated with an error exit status (1)

Command executed:

  perl /home/skyhorse/Desktop/lncpipe/LncPipe/bin/modifyDesign.pl design.file  > design.matrix 
  Rscript -e "library(LncPipeReporter);run_reporter(input='.', output = 'reporter.html',output_dir='./LncPipeReports',de.method='edger',theme = 'npg',cdf.percent = 10,max.lncrna.len = 10000,min.expressed.sample = 50, ask = FALSE)"

Command exit status:
  1

Command output:
    ordinary text without R code
  
  
    |                                                                       
    |..............................................................   |  95%
  label: lncRNA table
  
    |                                                                       
    |.................................................................| 100%
    ordinary text without R code
  
  
  
    |                                                                       
    |.............................................................    |  94%
    ordinary text without R code
  
  
    |                                                                       
    |.................................................................| 100%
  label: DE-child (with options) 
  List of 2
   $ child: language switch(de.method, edger = "edger.Rmd", deseq2 = "deseq2.Rmd", noiseq = "noiseq.Rmd")
   $ eval : language !is.null(type.list[["Design"]])
  
  
    |                                                                       
    |                                                                 |   0%
    |                                                                       
    |...                                                              |   5%
    ordinary text without R code
  
  
    |                                                                       
    |......                                                           |  10%
  label: setup (with options) 
  List of 1
   $ include: logi FALSE
  
  
    |                                                                       
    |..........                                                       |  15%
    ordinary text without R code
  
  
    |                                                                       
    |.............                                                    |  20%
  label: unnamed-chunk-11
  

Command error:
  
  
  processing file: reporter.Rmd
  
  
  processing file: ./Hisat2.Rmd
  
  
  processing file: ./lncRNA.Rmd
  
  
  processing file: ./edger.Rmd
  Quitting from lines 9-57 (./edger.Rmd) 
  Quitting from lines 250-255 (./edger.Rmd) 
  Error in `.rowNamesDF<-`(x, value = value) : 
    duplicate 'row.names' are not allowed
  Calls: run_reporter ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
  In addition: Warning messages:
  1: In eval(expr, envir, enclos) : NAs introduced by coercion
  2: non-unique values when setting 'row.names':  
  Execution halted

Work dir:
  /home/skyhorse/Desktop/lncpipe/LncPipe/work/9a/da60f7a01eefad36c0f8ef5880ceb5

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by bioinformatist** [comment]
@likelet check if test dataset is too small to finish testing?

**Comment by likelet** [comment]
@bihuaf hi, thanks for point this issue out, I will check the test example ASAP.

**Comment by bihuaf** [comment]
Hi, is it possible to fix the problem? Thank you.

**Comment by likelet** [comment]
@bihuaf sorry for the delayed reply. 
I have reproduced the error.  and found it may be due to the last update of the test dataset a few months before.  
The LncPipeReporter throws a duplicated rowname error during the differential expression analysis module in edgeR function, but the rownames were all unique in the current test case(the LncPipeReporter in docker image is not the latest version).  
you can copy the folder `/home/skyhorse/Desktop/lncpipe/LncPipe/work/9a/da60f7a01eefad36c0f8ef5880ceb5` out and rerun the lncPipeReporter with a local installed  lncPipeReporter R package (latest version, developed by @bioinformatist  ) by referring to this [page](https://github.com/bioinformatist/LncPipeReporter). 
On the other hand, I will update the lncPipeReporter in the docker image soon. 
plz let this issue open until the docker image is fixed then.

**Comment by bihuaf** [comment]
I will try lncPipeReporter R package. Thank you very much.

**Comment by bihuaf** [comment]
Hi,
I copied the folder (a4a43f4f5e3d20b30a911ddbe1ba59), which includes dPDLSCs1_abundance.tsv , dPDLSCs2_abundance.tsv , final_all.gtf , get_kallisto_matrix.Rout , kallisto.count.txt , kallisto.tpm.txt , map.file , uPDLSCs1_abundance.tsv , uPDLSCs2_abundance.tsv . is it the right folder?
After LncPipeReporter was installed, I tried  using "a4a43f4f5e3d20b30a911ddbe1ba59" to replace "extdata" and deleted "demo_results", but it did not work. How to do it? Looking  forward to your suggestion, thank you very much!

library(LncPipeReporter)

run_reporter(input = system.file(file.path("extdata", "demo_results"),package = "LncPipeReporter"),
             output = 'reporter.html',
             theme = 'npg',
             cdf.percent = 10,
             max.lncrna.len = 10000,
             min.expressed.sample = 50,
             ask = FALSE)

________________________________

**Comment by bioinformatist** [comment]
@bihuaf Can you bring us a tarball of your results, which might be used in LncPipeReporter?
You can just upload it here as attachment, or send me an email: sunyu2@sysucc.org.cn

**Comment by bihuaf** [comment]
The results are attached. If you need more data please let me know. Thank you!
________________________________
