### ISSUE TITLE
Error executing process > 'Identify_novel_lncRNA_with_criterions (1)'

### ISSUE THREAD

**Issue by drwazeem** [likelet/LncPipe#51]
In addition to one problem posted earlier, I have faced this problem more than a few times.

```
Error executing process > 'Identify_novel_lncRNA_with_criterions (1)'

Caused by:
  Process `Identify_novel_lncRNA_with_criterions (1)` terminated with an error exit status (1)

Command executed:

  # filtering novel lncRNA based on cuffmerged trascripts
  set -o pipefail
  awk '$3 =="x"||$3=="u"||$3=="i"{print $0}' merged_lncRNA.merged.gtf.tmap > novel.gtf.tmap
  #   excluding length smaller than 200 nt
  awk '$10 >200{print}' novel.gtf.tmap > novel.longRNA.gtf.tmap
  #   extract gtf
  awk '{print $5}' novel.longRNA.gtf.tmap |perl /media/wazeem/82346450346448ED/lncpipe/LncPipe/bin/extract_gtf_by_name.pl merged.gtf - >novel.longRNA.gtf
  awk '{if($3=="exon"){print $0}}' novel.longRNA.gtf > novel.longRNA.format.gtf 
  perl /media/wazeem/82346450346448ED/lncpipe/LncPipe/bin/get_exoncount.pl novel.longRNA.format.gtf  > novel.longRNA.exoncount.txt
  # gtf2gff3
  #check whether required
  # get fasta from gtf
  gffread novel.longRNA.gtf -g GRCm38.primary_assembly.genome.fa -w novel.longRNA.fa -W

Command exit status:
  1

Command output:
  (empty)

Command error:
  FASTA index file GRCm38.primary_assembly.genome.fa.fai created.
  Warning: couldn't find fasta record for '1'!
  Error: no genomic sequence available (check -g option!).

Work dir:
  /media/wazeem/82346450346448ED/lncpipe/LncPipe/work/cd/2ae35eeb1bc425fadf8625f078591f

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

This problem arises because stringtie doesn't add the prefix 'chr' to thegtf file it generates. novel.longRNA.gtf. I found  a workround i.e. editing the genome fasta file to remove 'chr' prefix but that stuff likely causes a problem somewhere else (not sure). Please check this issue as well.

**Comment by likelet** [comment]
hi @drwazeem 
Sorry for the late response. From your log, it seems an issue triggered by the inconsistent  reference fasta file and genome annotation file used in your analysis. Plz try to modify them or replace the file accordingly at the start of the analysis.
You may refer to  the test file format. 

Qi ZHao

**Comment by drwazeem** [comment]
Thank you @likelet 

Yes, I found a workaround on similar lines. There were other problems that I faced, one of which I have posted as another thread. However, I had to give up the idea of using the pipeline as the run used to terminate repeatedly. :( However, i expect to use the pipeline in future. Thanks once again.
