### ISSUE TITLE
singleend match error

### ISSUE THREAD

**Issue by kodayu** [likelet/LncPipe#6]
when I use the function of singleend, I suffered a problem.

fastqc -t 39 *_{1}_Clean.fastq.gz null

the work dir of this error is:  Jun 25 11:42 *_{1}_Clean.fastq.gz -> /data3/yukai/clean_data/wyn_m6a/116/*_{1}_Clean.fastq.gz

the * and {1} with an error match.

**Comment by likelet** [comment]
try *_clean.fastq.gz instead
