### ISSUE TITLE
Run_Kallisto_for_quantification terminated with an error exit status (137)

### ISSUE THREAD

**Issue by sateeshperi** [likelet/LncPipe#7]
I am currently trying to run LncPipe using the Docker image and I encountered the following error:

```
Aug-08 20:18:35.603 [Task monitor] ERROR nextflow.processor.TaskProcessor - Erro
r executing process > 'Run_kallisto_for_quantification (AAhu-FFinfer-TTsp-SS2)'

Caused by:
  Process `Run_kallisto_for_quantification (AAhu-FFinfer-TTsp-SS2)` terminated with an error exit status (137)

Command executed:

  #quantification by kallisto
  kallisto quant -i transcripts.idx -o AAhu-FFinfer-TTsp-SS2_kallisto -t 23 -b 100 AAhu-FFinfer-TTsp-SS2.R1.fq.gz AAhu-FFinfer-TTsp-SS2.R2.fq.gz
  mv AAhu-FFinfer-TTsp-SS2_kallisto/abundance.tsv AAhu-FFinfer-TTsp-SS2_abundance.tsv

Command exit status:
  137

Command output:
  (empty)

Command error:
 
  [quant] fragment length distribution will be estimated from the data
  [index] k-mer length: 31
  [index] number of targets: 213,479
  [index] number of k-mers: 614,018,229
  [index] number of equivalence classes: 3,877,325
  .command.sh: line 3:     9 Killed                  kallisto quant -i transcripts.idx -o AAhu-FFinfer-TTsp-SS2_kallisto -t 23 -b 100 AAhu-FFinfer-TTsp-SS2.R1.fq.gz AAhu-FFinfer-TTsp-SS2.R2.fq.gz
```

**Comment by likelet** [comment]
Hi sateeshperi 
Thanks for using lncPipe. It seems your error comes from exception of  `kallisto` step . 
Can you go to the working folder and check the the transcript.idx file. 
 Or you can send the `.nextflow.log` file in your current folder to me, I will check what's going on in your data. 

BTW, someone have reported an similar issue before privately and it often triggered by the limited available computing resource of your server  . Then a possible solution is to set the `maxForks ` parameter to 1 or 2 (default is 6) in your `nextflow.config` file, like below:
 ```
process {
   withLabel: para {
        maxForks = 2 
    }
    withLabel: 'qc' {
        maxForks = 6
    }
}
```

then rerun the lncpipe with `-resume`  to see whether it works.
Plz let me know how it is going

**Comment by likelet** [comment]
I try to reproduce your errors in a sever with  a limited resource, it throws the same error like you saw. 
 
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/3021506/43888774-16946bc8-9bf5-11e8-9a92-fc6392554665.png"> 

I reset the MaxForks parameter to 1, and it's ok now.  Try this ?

**Comment by sateeshperi** [comment]
Hi Qi Zhao, I figured it was a memory segmentation/handling issue for kallisto index on my system (as also referenced here: https://groups.google.com/forum/#!msg/kallisto-sleuth-users/ZDN3s-mSc8s/W0Ggq6jsAwAJ) but, didn't know how to adjust the parameters. Setting the MaxForks parameter to 2 in my docker.config seems to have fixed it. Thank you
