### ISSUE TITLE
non_model_organisms_CPAT_logitModels

### ISSUE THREAD

**Issue by sateeshperi** [likelet/LncPipe#9]
Hi, I was wondering if it would be possible to run LncPipe for non-model organisms (i'm interested in rat) if the CPAT logitModels (make_hexamer_tab.py & make_logitModel.py) are constructed separately and provided in the work directory?

**Comment by likelet** [comment]
sure，this is a good idea if you can build the CPAT model seperately. But it also need known protein coding and lncrna gtf to help  distinguish novel or known lncrnas. 

for your suggestion, it can be done by providing a model file path in nf file. i will show the modification later.

**Comment by likelet** [comment]
Here is the example that how to modify the code. 
In `nf file ` you can find the command that run CPAT in 
https://github.com/likelet/LncPipe/blob/cbe01af826c07df52bbc4f5e3a6ed8e53bbb6e41/LncRNAanalysisPipe.nf#L1029

for nonhuman 

https://github.com/likelet/LncPipe/blob/cbe01af826c07df52bbc4f5e3a6ed8e53bbb6e41/LncRNAanalysisPipe.nf#L1036

https://github.com/likelet/LncPipe/blob/cbe01af826c07df52bbc4f5e3a6ed8e53bbb6e41/LncRNAanalysisPipe.nf#L1044

https://github.com/likelet/LncPipe/blob/cbe01af826c07df52bbc4f5e3a6ed8e53bbb6e41/LncRNAanalysisPipe.nf#L1051

if you have logimodels for other non model organisms, you can specify the path of the model.  To note, `!{params.cpatpath}/dat/` can be changed into the path where you model is. 

LncPipe also call CPAT to assess the protein coding ability of identified Lncs and protein codings in summary step,  if you modified the code in the above lines, you need also edit the code in 

https://github.com/likelet/LncPipe/blob/cbe01af826c07df52bbc4f5e3a6ed8e53bbb6e41/LncRNAanalysisPipe.nf#L1159
